### ISSUE TITLE
兄弟打扰一下，求加入YouTube去广告规则。

### ISSUE THREAD

**Issue by sw19999** [ck629/Rules#1]
在adgurad home或者adblock plus加入以下规则可以去掉iOS App广告，希望兄弟能转换成小火箭的规则

/googleads.$~script,domain=~googleads.github.io
/pagead/lvz?
||google.com/pagead/
||static.doubleclick.net^$domain=youtube.com
||youtube.com/get_midroll_

**Comment by ligang2020** [comment]
同求
